(require 'tabbar)
(tabbar-mode)
;; (global-set-key (kbd "") 'tabbar-backward-group)
;; (global-set-key (kbd "") 'tabbar-forward-group)
;; (global-set-key (kbd "") 'tabbar-backward)
;; (global-set-key (kbd "") 'tabbar-forward)
